// Generated by Dagger (https://dagger.dev).
package com.example.finalproject.presentation.screen.browse;

import com.example.finalproject.domain.repository.MovieRepository;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
        "unchecked",
        "rawtypes"
})
public final class BrowseViewModel_Factory implements Factory<BrowseViewModel> {
  private final Provider<MovieRepository> repositoryProvider;

  public BrowseViewModel_Factory(Provider<MovieRepository> repositoryProvider) {
    this.repositoryProvider = repositoryProvider;
  }

  @Override
  public BrowseViewModel get() {
    return newInstance(repositoryProvider.get());
  }

  public static BrowseViewModel_Factory create(Provider<MovieRepository> repositoryProvider) {
    return new BrowseViewModel_Factory(repositoryProvider);
  }

  public static BrowseViewModel newInstance(MovieRepository repository) {
    return new BrowseViewModel(repository);
  }
}
