// Generated by Dagger (https://dagger.dev).
package com.example.finalproject.presentation.screen.browse;

import com.example.finalproject.presentation.image_loader.ImageLoader;
import dagger.MembersInjector;
import dagger.internal.DaggerGenerated;
import dagger.internal.InjectedFieldSignature;
import dagger.internal.QualifierMetadata;
import javax.inject.Provider;

@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
        "unchecked",
        "rawtypes"
})
public final class PopularFragment_MembersInjector implements MembersInjector<PopularFragment> {
  private final Provider<ImageLoader> imageLoaderProvider;

  public PopularFragment_MembersInjector(Provider<ImageLoader> imageLoaderProvider) {
    this.imageLoaderProvider = imageLoaderProvider;
  }

  public static MembersInjector<PopularFragment> create(Provider<ImageLoader> imageLoaderProvider) {
    return new PopularFragment_MembersInjector(imageLoaderProvider);
  }

  @Override
  public void injectMembers(PopularFragment instance) {
    injectImageLoader(instance, imageLoaderProvider.get());
  }

  @InjectedFieldSignature("com.example.finalproject.presentation.screen.browse.PopularFragment.imageLoader")
  public static void injectImageLoader(PopularFragment instance, ImageLoader imageLoader) {
    instance.imageLoader = imageLoader;
  }
}
