// Generated by Dagger (https://dagger.dev).
package com.example.finalproject.presentation.screen.detail;

import com.example.finalproject.presentation.image_loader.ImageLoader;
import dagger.MembersInjector;
import dagger.internal.DaggerGenerated;
import dagger.internal.InjectedFieldSignature;
import dagger.internal.QualifierMetadata;
import javax.inject.Provider;

@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
        "unchecked",
        "rawtypes"
})
public final class MovieDetailsFragment_MembersInjector implements MembersInjector<MovieDetailsFragment> {
  private final Provider<ImageLoader> imageLoaderProvider;

  public MovieDetailsFragment_MembersInjector(Provider<ImageLoader> imageLoaderProvider) {
    this.imageLoaderProvider = imageLoaderProvider;
  }

  public static MembersInjector<MovieDetailsFragment> create(
          Provider<ImageLoader> imageLoaderProvider) {
    return new MovieDetailsFragment_MembersInjector(imageLoaderProvider);
  }

  @Override
  public void injectMembers(MovieDetailsFragment instance) {
    injectImageLoader(instance, imageLoaderProvider.get());
  }

  @InjectedFieldSignature("com.example.finalproject.presentation.screen.detail.MovieDetailsFragment.imageLoader")
  public static void injectImageLoader(MovieDetailsFragment instance, ImageLoader imageLoader) {
    instance.imageLoader = imageLoader;
  }
}
