// Generated by Dagger (https://dagger.dev).
package com.example.finalproject.presentation.screen.detail;

import com.example.finalproject.presentation.image_loader.ImageLoader;
import dagger.MembersInjector;
import dagger.internal.DaggerGenerated;
import dagger.internal.InjectedFieldSignature;
import dagger.internal.QualifierMetadata;
import javax.inject.Provider;

@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
        "unchecked",
        "rawtypes"
})
public final class SimilarMoviesFragment_MembersInjector implements MembersInjector<SimilarMoviesFragment> {
  private final Provider<ImageLoader> imageLoaderProvider;

  public SimilarMoviesFragment_MembersInjector(Provider<ImageLoader> imageLoaderProvider) {
    this.imageLoaderProvider = imageLoaderProvider;
  }

  public static MembersInjector<SimilarMoviesFragment> create(
          Provider<ImageLoader> imageLoaderProvider) {
    return new SimilarMoviesFragment_MembersInjector(imageLoaderProvider);
  }

  @Override
  public void injectMembers(SimilarMoviesFragment instance) {
    injectImageLoader(instance, imageLoaderProvider.get());
  }

  @InjectedFieldSignature("com.example.finalproject.presentation.screen.detail.SimilarMoviesFragment.imageLoader")
  public static void injectImageLoader(SimilarMoviesFragment instance, ImageLoader imageLoader) {
    instance.imageLoader = imageLoader;
  }
}
