// Generated by Dagger (https://dagger.dev).
package com.example.finalproject.presentation.screen.home;

import com.example.finalproject.presentation.image_loader.ImageLoader;
import dagger.MembersInjector;
import dagger.internal.DaggerGenerated;
import dagger.internal.InjectedFieldSignature;
import dagger.internal.QualifierMetadata;
import javax.inject.Provider;

@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
        "unchecked",
        "rawtypes"
})
public final class HomeFragment_MembersInjector implements MembersInjector<HomeFragment> {
  private final Provider<ImageLoader> imageLoaderProvider;

  public HomeFragment_MembersInjector(Provider<ImageLoader> imageLoaderProvider) {
    this.imageLoaderProvider = imageLoaderProvider;
  }

  public static MembersInjector<HomeFragment> create(Provider<ImageLoader> imageLoaderProvider) {
    return new HomeFragment_MembersInjector(imageLoaderProvider);
  }

  @Override
  public void injectMembers(HomeFragment instance) {
    injectImageLoader(instance, imageLoaderProvider.get());
  }

  @InjectedFieldSignature("com.example.finalproject.presentation.screen.home.HomeFragment.imageLoader")
  public static void injectImageLoader(HomeFragment instance, ImageLoader imageLoader) {
    instance.imageLoader = imageLoader;
  }
}
