// Generated by Dagger (https://dagger.dev).
package com.example.finalproject.presentation.screen.my_lists;

import com.example.finalproject.domain.repository.MovieRepository;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
        "unchecked",
        "rawtypes"
})
public final class MyListsViewModel_Factory implements Factory<MyListsViewModel> {
  private final Provider<MovieRepository> repositoryProvider;

  public MyListsViewModel_Factory(Provider<MovieRepository> repositoryProvider) {
    this.repositoryProvider = repositoryProvider;
  }

  @Override
  public MyListsViewModel get() {
    return newInstance(repositoryProvider.get());
  }

  public static MyListsViewModel_Factory create(Provider<MovieRepository> repositoryProvider) {
    return new MyListsViewModel_Factory(repositoryProvider);
  }

  public static MyListsViewModel newInstance(MovieRepository repository) {
    return new MyListsViewModel(repository);
  }
}
