// Generated by Dagger (https://dagger.dev).
package com.example.finalproject.presentation.screen.my_lists;

import com.example.finalproject.presentation.image_loader.ImageLoader;
import dagger.MembersInjector;
import dagger.internal.DaggerGenerated;
import dagger.internal.InjectedFieldSignature;
import dagger.internal.QualifierMetadata;
import javax.inject.Provider;

@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
        "unchecked",
        "rawtypes"
})
public final class PersonalListFragment_MembersInjector implements MembersInjector<PersonalListFragment> {
  private final Provider<ImageLoader> imageLoaderProvider;

  public PersonalListFragment_MembersInjector(Provider<ImageLoader> imageLoaderProvider) {
    this.imageLoaderProvider = imageLoaderProvider;
  }

  public static MembersInjector<PersonalListFragment> create(
          Provider<ImageLoader> imageLoaderProvider) {
    return new PersonalListFragment_MembersInjector(imageLoaderProvider);
  }

  @Override
  public void injectMembers(PersonalListFragment instance) {
    injectImageLoader(instance, imageLoaderProvider.get());
  }

  @InjectedFieldSignature("com.example.finalproject.presentation.screen.my_lists.PersonalListFragment.imageLoader")
  public static void injectImageLoader(PersonalListFragment instance, ImageLoader imageLoader) {
    instance.imageLoader = imageLoader;
  }
}
