// Generated by Dagger (https://dagger.dev).
package com.example.finalproject.presentation.screen.my_lists;

import com.example.finalproject.presentation.image_loader.ImageLoader;
import dagger.MembersInjector;
import dagger.internal.DaggerGenerated;
import dagger.internal.InjectedFieldSignature;
import dagger.internal.QualifierMetadata;
import javax.inject.Provider;

@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
        "unchecked",
        "rawtypes"
})
public final class WatchListFragment_MembersInjector implements MembersInjector<WatchListFragment> {
  private final Provider<ImageLoader> imageLoaderProvider;

  public WatchListFragment_MembersInjector(Provider<ImageLoader> imageLoaderProvider) {
    this.imageLoaderProvider = imageLoaderProvider;
  }

  public static MembersInjector<WatchListFragment> create(
          Provider<ImageLoader> imageLoaderProvider) {
    return new WatchListFragment_MembersInjector(imageLoaderProvider);
  }

  @Override
  public void injectMembers(WatchListFragment instance) {
    injectImageLoader(instance, imageLoaderProvider.get());
  }

  @InjectedFieldSignature("com.example.finalproject.presentation.screen.my_lists.WatchListFragment.imageLoader")
  public static void injectImageLoader(WatchListFragment instance, ImageLoader imageLoader) {
    instance.imageLoader = imageLoader;
  }
}
